# Generated by Django 4.2.4 on 2023-08-25 09:55

from django.db import migrations

def populate_data(apps, schema_editor):
    Category = apps.get_model("restaurant", "Category")

    Category.objects.create(name='Breakfast')
    Category.objects.create(name='Lunch')
    Category.objects.create(name='Dinner')
    Category.objects.create(name='Desserts')
    Category.objects.create(name='Drinks')

class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_order_restaurant'),
    ]

    operations = [
        migrations.RunPython(populate_data),
    ]

